name: macOS C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0' # runs at 00:00 on every Sunday

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install llvm
        brew install cmake
        brew install emscripten
        brew install assimp
        brew install yarn
        brew install boost
        brew install eigen
        brew install cgal
        brew install googletest
        brew install ninja

    - name: Set environment
      run: |
        LLVM_PATH=$(brew --prefix llvm)
        echo "CC=$LLVM_PATH/bin/clang" >> $GITHUB_ENV
        echo "CXX=$LLVM_PATH/bin/clang++" >> $GITHUB_ENV

    - name: Build 2DTissue
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_STANDARD=20 -G Ninja ..
        ninja

    - name: Test
      run: ./build/all_tests
