name: Ubuntu C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm libassimp-dev clang emscripten yarn cmake libboost-all-dev libeigen3-dev libgmp-dev libmpfr-dev libcgal-dev googletest

    - name: Configure
      run: |
        sudo update-alternatives --install /usr/bin/cc cc $(which clang) 100
        sudo update-alternatives --install /usr/bin/c++ c++ $(which clang++) 100
        mkdir build
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-O2"

    - name: Build
      run: |
        make -C build -j $(nproc)

    - name: Test
      run: |
        ./build/all_tests